export type CollegeSeed = {
  slug: string;
  name: string;
  city: string;
  state: string;
  type: string;
  feesPerYear: number;
  rating: number;
  overview: string;
  established: number;
  accreditation: string;
  website: string;
  courses: { name: string; degree: string; duration: string; feesPerYear: number; seats: number }[];
  placement: {
    year: number;
    avgPackage: number;
    highestPackage: number;
    placementRate: number;
    topRecruiters: string[];
  };
  reviews: { authorName: string; rating: number; title: string; content: string }[];
};

/** 30 additional colleges — AKTU, state universities, and regional institutes */
export const extraColleges: CollegeSeed[] = [
  {
    slug: "aktu-lucknow",
    name: "Dr. A.P.J. Abdul Kalam Technical University",
    city: "Lucknow",
    state: "Uttar Pradesh",
    type: "State Technical University",
    feesPerYear: 120000,
    rating: 4.2,
    established: 2000,
    accreditation: "NAAC A",
    website: "https://aktu.ac.in",
    overview:
      "AKTU (formerly UPTU) is Uttar Pradesh's apex technical university affiliating 800+ engineering and management colleges. Its curriculum shapes UP's vast engineering ecosystem.",
    courses: [
      { name: "Computer Science & Engineering", degree: "B.Tech", duration: "4 years", feesPerYear: 120000, seats: 200 },
      { name: "Information Technology", degree: "B.Tech", duration: "4 years", feesPerYear: 120000, seats: 180 },
    ],
    placement: { year: 2025, avgPackage: 5.5, highestPackage: 24, placementRate: 75.0, topRecruiters: ["TCS", "Infosys", "HCL", "Wipro"] },
    reviews: [{ authorName: "Ravi U.", rating: 4.1, title: "UP's engineering hub", content: "Central university for UP technical education with wide affiliated college network." }],
  },
  {
    slug: "hbtu-kanpur",
    name: "Harcourt Butler Technical University",
    city: "Kanpur",
    state: "Uttar Pradesh",
    type: "State University",
    feesPerYear: 95000,
    rating: 4.38,
    established: 1921,
    accreditation: "NAAC A",
    website: "https://hbtu.ac.in",
    overview:
      "HBTU Kanpur is a premier AKTU-era state technical university with affordable fees and strong chemical, leather, and computer engineering programs.",
    courses: [
      { name: "Computer Science & Engineering", degree: "B.Tech", duration: "4 years", feesPerYear: 95000, seats: 120 },
      { name: "Chemical Engineering", degree: "B.Tech", duration: "4 years", feesPerYear: 95000, seats: 90 },
    ],
    placement: { year: 2025, avgPackage: 7.2, highestPackage: 28, placementRate: 83.0, topRecruiters: ["TCS", "Reliance", "ITC", "Asian Paints"] },
    reviews: [{ authorName: "Suresh K.", rating: 4.3, title: "Solid UP government option", content: "Good value with respected legacy in Kanpur industrial belt." }],
  },
  {
    slug: "kiet-ghaziabad",
    name: "KIET Group of Institutions",
    city: "Ghaziabad",
    state: "Uttar Pradesh",
    type: "AKTU Affiliated",
    feesPerYear: 145000,
    rating: 4.25,
    established: 1998,
    accreditation: "NAAC A",
    website: "https://kiet.edu",
    overview:
      "KIET Ghaziabad is among the top AKTU-affiliated private colleges in NCR with consistent placements in IT and core engineering for Delhi-NCR students.",
    courses: [
      { name: "Computer Science & Engineering", degree: "B.Tech", duration: "4 years", feesPerYear: 145000, seats: 300 },
      { name: "Electronics & Communication", degree: "B.Tech", duration: "4 years", feesPerYear: 145000, seats: 240 },
    ],
    placement: { year: 2025, avgPackage: 6.8, highestPackage: 32, placementRate: 84.0, topRecruiters: ["Infosys", "Cognizant", "Capgemini", "Genpact"] },
    reviews: [{ authorName: "Neetu S.", rating: 4.2, title: "Top AKTU college", content: "Strong training and placement cell for NCR students." }],
  },
  {
    slug: "abes-ghaziabad",
    name: "ABES Engineering College",
    city: "Ghaziabad",
    state: "Uttar Pradesh",
    type: "AKTU Affiliated",
    feesPerYear: 138000,
    rating: 4.22,
    established: 2000,
    accreditation: "NAAC A",
    website: "https://abes.ac.in",
    overview:
      "ABES EC is a leading AKTU-affiliated institute in Ghaziabad known for disciplined academics and steady placement records in software services.",
    courses: [
      { name: "Computer Science & Engineering", degree: "B.Tech", duration: "4 years", feesPerYear: 138000, seats: 360 },
      { name: "Information Technology", degree: "B.Tech", duration: "4 years", feesPerYear: 138000, seats: 180 },
    ],
    placement: { year: 2025, avgPackage: 6.2, highestPackage: 28, placementRate: 82.0, topRecruiters: ["TCS", "Wipro", "Accenture", "HCL"] },
    reviews: [{ authorName: "Mohit A.", rating: 4.1, title: "Reliable AKTU pick", content: "Good infrastructure and placement support for CSE/IT branches." }],
  },
  {
    slug: "galgotias-greater-noida",
    name: "Galgotias College of Engineering and Technology",
    city: "Greater Noida",
    state: "Uttar Pradesh",
    type: "AKTU Affiliated",
    feesPerYear: 155000,
    rating: 4.18,
    established: 2000,
    accreditation: "NAAC A+",
    website: "https://www.galgotiasuniversity.edu.in",
    overview:
      "Galgotias is a prominent NCR institution (now university status) with large intake and industry-oriented programs popular among UPSEE/JEE students.",
    courses: [
      { name: "Computer Science & Engineering", degree: "B.Tech", duration: "4 years", feesPerYear: 155000, seats: 420 },
      { name: "Artificial Intelligence & ML", degree: "B.Tech", duration: "4 years", feesPerYear: 155000, seats: 120 },
    ],
    placement: { year: 2025, avgPackage: 5.9, highestPackage: 30, placementRate: 80.0, topRecruiters: ["Infosys", "IBM", "Cognizant", "Amazon"] },
    reviews: [{ authorName: "Pallavi G.", rating: 4.0, title: "Large campus", content: "Many opportunities for extracurriculars; verify branch-wise placement data." }],
  },
  {
    slug: "mmmut-gorakhpur",
    name: "Madan Mohan Malaviya University of Technology",
    city: "Gorakhpur",
    state: "Uttar Pradesh",
    type: "State University",
    feesPerYear: 88000,
    rating: 4.35,
    established: 2013,
    accreditation: "NAAC A",
    website: "https://www.mmmut.ac.in",
    overview:
      "MMMUT Gorakhpur (formerly MMM Engineering College) is eastern UP's leading state technical university with affordable fees and growing placement outcomes.",
    courses: [
      { name: "Computer Science & Engineering", degree: "B.Tech", duration: "4 years", feesPerYear: 88000, seats: 150 },
      { name: "Mechanical Engineering", degree: "B.Tech", duration: "4 years", feesPerYear: 88000, seats: 120 },
    ],
    placement: { year: 2025, avgPackage: 6.5, highestPackage: 26, placementRate: 81.0, topRecruiters: ["TCS", "Infosys", "L&T", "BHEL"] },
    reviews: [{ authorName: "Akhilesh P.", rating: 4.3, title: "Eastern UP gem", content: "Best government technical option in Gorakhpur region." }],
  },
  {
    slug: "psit-kanpur",
    name: "Pranveer Singh Institute of Technology",
    city: "Kanpur",
    state: "Uttar Pradesh",
    type: "AKTU Affiliated",
    feesPerYear: 132000,
    rating: 4.15,
    established: 2004,
    accreditation: "NAAC A",
    website: "https://psit.ac.in",
    overview:
      "PSIT Kanpur is a well-known AKTU-affiliated college with focus on employability skills and NCR-level placement training for UP students.",
    courses: [
      { name: "Computer Science & Engineering", degree: "B.Tech", duration: "4 years", feesPerYear: 132000, seats: 300 },
      { name: "Electrical Engineering", degree: "B.Tech", duration: "4 years", feesPerYear: 132000, seats: 180 },
    ],
    placement: { year: 2025, avgPackage: 5.5, highestPackage: 22, placementRate: 78.0, topRecruiters: ["TCS", "Capgemini", "Infosys", "Genpact"] },
    reviews: [{ authorName: "Divya R.", rating: 4.0, title: "Decent AKTU choice", content: "Active placement cell and coding culture for CSE students." }],
  },
  {
    slug: "lucknow-university",
    name: "University of Lucknow",
    city: "Lucknow",
    state: "Uttar Pradesh",
    type: "State University",
    feesPerYear: 45000,
    rating: 4.28,
    established: 1921,
    accreditation: "NAAC A++",
    website: "https://www.lkouniv.ac.in",
    overview:
      "Lucknow University is a historic state university offering science, commerce, and emerging technology programs with very affordable fees for UP students.",
    courses: [
      { name: "Computer Science", degree: "B.Sc", duration: "3 years", feesPerYear: 45000, seats: 60 },
      { name: "Information Technology", degree: "BCA", duration: "3 years", feesPerYear: 45000, seats: 80 },
    ],
    placement: { year: 2025, avgPackage: 4.5, highestPackage: 12, placementRate: 68.0, topRecruiters: ["TCS", "Startups", "Banks", "UP Government"] },
    reviews: [{ authorName: "Imran L.", rating: 4.2, title: "Affordable and respected", content: "Strong humanities and science legacy with growing tech programs." }],
  },
  {
    slug: "bundelkhand-university",
    name: "Bundelkhand University",
    city: "Jhansi",
    state: "Uttar Pradesh",
    type: "State University",
    feesPerYear: 38000,
    rating: 4.05,
    established: 1975,
    accreditation: "NAAC B++",
    website: "https://bujhansi.ac.in",
    overview:
      "Bundelkhand University serves Jhansi and surrounding districts with affordable undergraduate programs including engineering through affiliated institutes.",
    courses: [
      { name: "Computer Science", degree: "B.Sc", duration: "3 years", feesPerYear: 38000, seats: 50 },
      { name: "Electronics", degree: "B.Sc", duration: "3 years", feesPerYear: 38000, seats: 40 },
    ],
    placement: { year: 2025, avgPackage: 3.8, highestPackage: 10, placementRate: 62.0, topRecruiters: ["TCS", "Local IT", "Banks", "Government"] },
    reviews: [{ authorName: "Ramesh B.", rating: 3.9, title: "Regional university", content: "Good for students seeking low-cost education in Bundelkhand." }],
  },
  {
    slug: "ccsu-meerut",
    name: "Chaudhary Charan Singh University",
    city: "Meerut",
    state: "Uttar Pradesh",
    type: "State University",
    feesPerYear: 42000,
    rating: 4.12,
    established: 1965,
    accreditation: "NAAC A",
    website: "https://www.ccsuniversity.ac.in",
    overview:
      "CCS University Meerut is western UP's major state university affiliating hundreds of colleges across Meerut, Ghaziabad, and surrounding districts.",
    courses: [
      { name: "Computer Science", degree: "B.Sc", duration: "3 years", feesPerYear: 42000, seats: 80 },
      { name: "Information Technology", degree: "BCA", duration: "3 years", feesPerYear: 42000, seats: 100 },
    ],
    placement: { year: 2025, avgPackage: 4.2, highestPackage: 14, placementRate: 65.0, topRecruiters: ["TCS", "Wipro", "Local Industry", "BPO"] },
    reviews: [{ authorName: "Sonia M.", rating: 4.0, title: "Wide reach in western UP", content: "Large affiliated network with accessible fee structure." }],
  },
  {
    slug: "mjpru-bareilly",
    name: "M.J.P. Rohilkhand University",
    city: "Bareilly",
    state: "Uttar Pradesh",
    type: "State University",
    feesPerYear: 40000,
    rating: 4.08,
    established: 1975,
    accreditation: "NAAC B++",
    website: "https://www.mjpru.ac.in",
    overview:
      "MJPRU Bareilly serves Rohilkhand region with arts, science, and professional programs through campus and affiliated colleges.",
    courses: [
      { name: "Computer Science", degree: "B.Sc", duration: "3 years", feesPerYear: 40000, seats: 60 },
      { name: "Information Technology", degree: "BCA", duration: "3 years", feesPerYear: 40000, seats: 80 },
    ],
    placement: { year: 2025, avgPackage: 4.0, highestPackage: 11, placementRate: 60.0, topRecruiters: ["TCS", "Banks", "Retail", "Government"] },
    reviews: [{ authorName: "Kunal B.", rating: 3.9, title: "Regional access", content: "Practical choice for Bareilly and nearby district students." }],
  },
  {
    slug: "ggsipu-delhi",
    name: "Guru Gobind Singh Indraprastha University",
    city: "New Delhi",
    state: "Delhi",
    type: "State University",
    feesPerYear: 135000,
    rating: 4.32,
    established: 1998,
    accreditation: "NAAC A",
    website: "https://www.ipu.ac.in",
    overview:
      "GGSIPU is Delhi's state university conducting CET for engineering, law, and management across dozens of affiliated institutes in the capital.",
    courses: [
      { name: "Computer Science & Engineering", degree: "B.Tech", duration: "4 years", feesPerYear: 135000, seats: 180 },
      { name: "Information Technology", degree: "B.Tech", duration: "4 years", feesPerYear: 135000, seats: 120 },
    ],
    placement: { year: 2025, avgPackage: 7.8, highestPackage: 35, placementRate: 82.0, topRecruiters: ["Deloitte", "TCS", "Startups", "EY"] },
    reviews: [{ authorName: "Tarun D.", rating: 4.2, title: "Delhi state option", content: "Good affiliated colleges like USICT and MSIT offer strong outcomes." }],
  },
  {
    slug: "amu-aligarh",
    name: "Aligarh Muslim University",
    city: "Aligarh",
    state: "Uttar Pradesh",
    type: "Central University",
    feesPerYear: 55000,
    rating: 4.45,
    established: 1920,
    accreditation: "NAAC A++",
    website: "https://www.amu.ac.in",
    overview:
      "AMU is a prestigious central university with Zakir Hussain College of Engineering and Technology offering affordable quality engineering education.",
    courses: [
      { name: "Computer Science & Engineering", degree: "B.Tech", duration: "4 years", feesPerYear: 55000, seats: 90 },
      { name: "Electronics Engineering", degree: "B.Tech", duration: "4 years", feesPerYear: 55000, seats: 75 },
    ],
    placement: { year: 2025, avgPackage: 8.5, highestPackage: 38, placementRate: 85.0, topRecruiters: ["TCS", "Microsoft", "Oracle", "Public Sector"] },
    reviews: [{ authorName: "Asad K.", rating: 4.5, title: "Historic institution", content: "Excellent value as a central university with strong alumni network." }],
  },
  {
    slug: "bhu-varanasi",
    name: "Banaras Hindu University",
    city: "Varanasi",
    state: "Uttar Pradesh",
    type: "Central University",
    feesPerYear: 48000,
    rating: 4.52,
    established: 1916,
    accreditation: "NAAC A++",
    website: "https://www.bhu.ac.in",
    overview:
      "BHU is one of India's largest residential universities with IIT-BHU and IMS alongside arts, sciences, and medicine on a single sprawling campus.",
    courses: [
      { name: "Pharmaceutical Sciences", degree: "B.Pharm", duration: "4 years", feesPerYear: 48000, seats: 80 },
      { name: "Agriculture", degree: "B.Sc", duration: "4 years", feesPerYear: 48000, seats: 60 },
    ],
    placement: { year: 2025, avgPackage: 7.0, highestPackage: 30, placementRate: 78.0, topRecruiters: ["Pharma Cos", "Research Labs", "Government", "IT"] },
    reviews: [{ authorName: "Shivam V.", rating: 4.5, title: "Complete campus life", content: "Unique blend of tradition, research, and multidisciplinary learning." }],
  },
  {
    slug: "jamia-delhi",
    name: "Jamia Millia Islamia",
    city: "New Delhi",
    state: "Delhi",
    type: "Central University",
    feesPerYear: 52000,
    rating: 4.4,
    established: 1920,
    accreditation: "NAAC A++",
    website: "https://www.jmi.ac.in",
    overview:
      "Jamia Millia Islamia is a central university in Delhi with respected engineering, architecture, and mass communication programs.",
    courses: [
      { name: "Computer Engineering", degree: "B.Tech", duration: "4 years", feesPerYear: 52000, seats: 70 },
      { name: "Electronics & Communication", degree: "B.Tech", duration: "4 years", feesPerYear: 52000, seats: 60 },
    ],
    placement: { year: 2025, avgPackage: 8.0, highestPackage: 40, placementRate: 84.0, topRecruiters: ["Adobe", "Samsung", "Deloitte", "Startups"] },
    reviews: [{ authorName: "Zara H.", rating: 4.4, title: "Delhi central gem", content: "Affordable fees with strong faculty in engineering and media." }],
  },
  {
    slug: "rtu-kota",
    name: "Rajasthan Technical University",
    city: "Kota",
    state: "Rajasthan",
    type: "State Technical University",
    feesPerYear: 90000,
    rating: 4.15,
    established: 2006,
    accreditation: "NAAC B++",
    website: "https://www.rtu.ac.in",
    overview:
      "RTU Kota is Rajasthan's technical university affiliating engineering colleges statewide and conducting REAP admissions for the state.",
    courses: [
      { name: "Computer Science & Engineering", degree: "B.Tech", duration: "4 years", feesPerYear: 90000, seats: 150 },
      { name: "Information Technology", degree: "B.Tech", duration: "4 years", feesPerYear: 90000, seats: 120 },
    ],
    placement: { year: 2025, avgPackage: 5.2, highestPackage: 20, placementRate: 72.0, topRecruiters: ["TCS", "Infosys", "Cement Cos", "Startups"] },
    reviews: [{ authorName: "Vivek R.", rating: 4.0, title: "Rajasthan's tech hub", content: "Central body for Rajasthan engineering admissions and curriculum." }],
  },
  {
    slug: "mnit-jaipur",
    name: "Malaviya National Institute of Technology Jaipur",
    city: "Jaipur",
    state: "Rajasthan",
    type: "NIT",
    feesPerYear: 160000,
    rating: 4.46,
    established: 1963,
    accreditation: "NAAC A+",
    website: "https://mnit.ac.in",
    overview:
      "MNIT Jaipur is Rajasthan's NIT with strong placements in IT and core engineering, popular among JEE Main students in North India.",
    courses: [
      { name: "Computer Science & Engineering", degree: "B.Tech", duration: "4 years", feesPerYear: 160000, seats: 130 },
      { name: "Electronics & Communication", degree: "B.Tech", duration: "4 years", feesPerYear: 160000, seats: 110 },
    ],
    placement: { year: 2025, avgPackage: 13.0, highestPackage: 48, placementRate: 89.0, topRecruiters: ["Microsoft", "Oracle", "Samsung", "Adobe"] },
    reviews: [{ authorName: "Pooja J.", rating: 4.4, title: "Rajasthan's top NIT", content: "Great campus life in Jaipur with improving placement stats yearly." }],
  },
  {
    slug: "gtu-ahmedabad",
    name: "Gujarat Technological University",
    city: "Ahmedabad",
    state: "Gujarat",
    type: "State Technical University",
    feesPerYear: 85000,
    rating: 4.1,
    established: 2007,
    accreditation: "NAAC B++",
    website: "https://www.gtu.ac.in",
    overview:
      "GTU Ahmedabad affiliates Gujarat's engineering and pharmacy colleges, setting curriculum for the state's large technical education network.",
    courses: [
      { name: "Computer Engineering", degree: "B.E.", duration: "4 years", feesPerYear: 85000, seats: 200 },
      { name: "Information Technology", degree: "B.E.", duration: "4 years", feesPerYear: 85000, seats: 150 },
    ],
    placement: { year: 2025, avgPackage: 5.0, highestPackage: 22, placementRate: 74.0, topRecruiters: ["TCS", "Adani", "Zydus", "Startups"] },
    reviews: [{ authorName: "Hiral G.", rating: 4.0, title: "Gujarat's apex tech body", content: "Affiliates top colleges like LDCE and Nirma across the state." }],
  },
  {
    slug: "sppu-pune",
    name: "Savitribai Phule Pune University",
    city: "Pune",
    state: "Maharashtra",
    type: "State University",
    feesPerYear: 65000,
    rating: 4.35,
    established: 1949,
    accreditation: "NAAC A+",
    website: "https://www.unipune.ac.in",
    overview:
      "SPPU Pune is one of Maharashtra's largest universities affiliating engineering, science, and arts colleges across Pune and surrounding districts.",
    courses: [
      { name: "Computer Science", degree: "B.Sc", duration: "3 years", feesPerYear: 65000, seats: 80 },
      { name: "Information Technology", degree: "B.Sc", duration: "3 years", feesPerYear: 65000, seats: 60 },
    ],
    placement: { year: 2025, avgPackage: 6.0, highestPackage: 25, placementRate: 76.0, topRecruiters: ["TCS", "Bajaj", "Startups", "IT Services"] },
    reviews: [{ authorName: "Ajay P.", rating: 4.3, title: "Pune's university hub", content: "Oxford of the East legacy with strong affiliated engineering colleges." }],
  },
  {
    slug: "mumbai-university",
    name: "University of Mumbai",
    city: "Mumbai",
    state: "Maharashtra",
    type: "State University",
    feesPerYear: 55000,
    rating: 4.3,
    established: 1857,
    accreditation: "NAAC A",
    website: "https://mu.ac.in",
    overview:
      "Mumbai University affiliates engineering colleges including DJ Sanghvi and KJ Somaiya, serving India's financial capital's student population.",
    courses: [
      { name: "Computer Engineering", degree: "B.E.", duration: "4 years", feesPerYear: 55000, seats: 120 },
      { name: "Information Technology", degree: "B.E.", duration: "4 years", feesPerYear: 55000, seats: 100 },
    ],
    placement: { year: 2025, avgPackage: 7.5, highestPackage: 35, placementRate: 80.0, topRecruiters: ["Banks", "TCS", "Fintech", "Startups"] },
    reviews: [{ authorName: "Rhea M.", rating: 4.2, title: "Mumbai's academic anchor", content: "Access to Mumbai's industry through top affiliated institutes." }],
  },
  {
    slug: "osmania-hyderabad",
    name: "Osmania University College of Engineering",
    city: "Hyderabad",
    state: "Telangana",
    type: "State University",
    feesPerYear: 72000,
    rating: 4.28,
    established: 1929,
    accreditation: "NAAC A",
    website: "https://www.osmania.ac.in",
    overview:
      "Osmania University is Telangana's historic state university with a respected engineering college offering affordable technical education.",
    courses: [
      { name: "Computer Science & Engineering", degree: "B.E.", duration: "4 years", feesPerYear: 72000, seats: 120 },
      { name: "Electronics & Communication", degree: "B.E.", duration: "4 years", feesPerYear: 72000, seats: 100 },
    ],
    placement: { year: 2025, avgPackage: 6.5, highestPackage: 28, placementRate: 78.0, topRecruiters: ["TCS", "Cyient", "Deloitte", "Startups"] },
    reviews: [{ authorName: "Charan T.", rating: 4.2, title: "Hyderabad heritage", content: "Affordable state option with Hyderabad's growing tech job market." }],
  },
  {
    slug: "andhra-university",
    name: "Andhra University College of Engineering",
    city: "Visakhapatnam",
    state: "Andhra Pradesh",
    type: "State University",
    feesPerYear: 68000,
    rating: 4.25,
    established: 1955,
    accreditation: "NAAC A",
    website: "https://www.andhrauniversity.edu.in",
    overview:
      "Andhra University is among India's oldest universities with a strong engineering college serving coastal Andhra and Vizag's industrial corridor.",
    courses: [
      { name: "Computer Science & Engineering", degree: "B.Tech", duration: "4 years", feesPerYear: 68000, seats: 120 },
      { name: "Civil Engineering", degree: "B.Tech", duration: "4 years", feesPerYear: 68000, seats: 90 },
    ],
    placement: { year: 2025, avgPackage: 5.8, highestPackage: 24, placementRate: 75.0, topRecruiters: ["TCS", "Naval Dockyard", "Steel Plants", "IT"] },
    reviews: [{ authorName: "Srinivas A.", rating: 4.2, title: "Coastal AP leader", content: "Respected government university with Vizag port city advantages." }],
  },
  {
    slug: "cusat-kochi",
    name: "Cochin University of Science and Technology",
    city: "Kochi",
    state: "Kerala",
    type: "State University",
    feesPerYear: 75000,
    rating: 4.38,
    established: 1971,
    accreditation: "NAAC A",
    website: "https://www.cusat.ac.in",
    overview:
      "CUSAT Kochi is Kerala's premier science and technology university with SOE Pulinkunnu and main campus programs in engineering and marine sciences.",
    courses: [
      { name: "Computer Science & Engineering", degree: "B.Tech", duration: "4 years", feesPerYear: 75000, seats: 90 },
      { name: "Safety & Fire Engineering", degree: "B.Tech", duration: "4 years", feesPerYear: 75000, seats: 60 },
    ],
    placement: { year: 2025, avgPackage: 6.8, highestPackage: 30, placementRate: 80.0, topRecruiters: ["TCS", "UST", "Shipyards", "IT"] },
    reviews: [{ authorName: "Anu K.", rating: 4.3, title: "Kerala tech hub", content: "Strong in marine and safety engineering alongside CSE." }],
  },
  {
    slug: "calcutta-university",
    name: "University of Calcutta",
    city: "Kolkata",
    state: "West Bengal",
    type: "State University",
    feesPerYear: 35000,
    rating: 4.35,
    established: 1857,
    accreditation: "NAAC A++",
    website: "https://www.caluniv.ac.in",
    overview:
      "Calcutta University is one of Asia's oldest modern universities with Institute of Engineering and affiliated colleges across Kolkata.",
    courses: [
      { name: "Computer Science", degree: "B.Sc", duration: "3 years", feesPerYear: 35000, seats: 60 },
      { name: "Information Technology", degree: "BCA", duration: "3 years", feesPerYear: 35000, seats: 80 },
    ],
    placement: { year: 2025, avgPackage: 5.5, highestPackage: 22, placementRate: 72.0, topRecruiters: ["TCS", "Banks", "Startups", "Analytics"] },
    reviews: [{ authorName: "Debjani C.", rating: 4.3, title: "Historic Kolkata uni", content: "Affordable with strong science and analytics pathways." }],
  },
  {
    slug: "panjab-university",
    name: "Panjab University",
    city: "Chandigarh",
    state: "Punjab",
    type: "State University",
    feesPerYear: 58000,
    rating: 4.4,
    established: 1947,
    accreditation: "NAAC A++",
    website: "https://puchd.ac.in",
    overview:
      "Panjab University in Chandigarh is a leading state university with UIET offering quality engineering at moderate fees in a planned city.",
    courses: [
      { name: "Computer Science & Engineering", degree: "B.E.", duration: "4 years", feesPerYear: 58000, seats: 90 },
      { name: "Electronics & Communication", degree: "B.E.", duration: "4 years", feesPerYear: 58000, seats: 75 },
    ],
    placement: { year: 2025, avgPackage: 7.0, highestPackage: 32, placementRate: 82.0, topRecruiters: ["TCS", "Samsung", "Startups", "Government"] },
    reviews: [{ authorName: "Gurleen S.", rating: 4.4, title: "Chandigarh advantage", content: "UIET is a hidden gem with great city campus life." }],
  },
  {
    slug: "nit-durgapur",
    name: "National Institute of Technology Durgapur",
    city: "Durgapur",
    state: "West Bengal",
    type: "NIT",
    feesPerYear: 158000,
    rating: 4.42,
    established: 1960,
    accreditation: "NAAC A+",
    website: "https://www.nitdgp.ac.in",
    overview:
      "NIT Durgapur is eastern India's established NIT with solid placements in software and manufacturing sectors for Bengal and Jharkhand students.",
    courses: [
      { name: "Computer Science & Engineering", degree: "B.Tech", duration: "4 years", feesPerYear: 158000, seats: 120 },
      { name: "Mechanical Engineering", degree: "B.Tech", duration: "4 years", feesPerYear: 158000, seats: 100 },
    ],
    placement: { year: 2025, avgPackage: 11.5, highestPackage: 42, placementRate: 87.0, topRecruiters: ["TCS", "Microsoft", "L&T", "Cognizant"] },
    reviews: [{ authorName: "Abhishek D.", rating: 4.3, title: "Solid eastern NIT", content: "Good ROI with improving CS placement trends." }],
  },
  {
    slug: "nit-rourkela",
    name: "National Institute of Technology Rourkela",
    city: "Rourkela",
    state: "Odisha",
    type: "NIT",
    feesPerYear: 162000,
    rating: 4.5,
    established: 1961,
    accreditation: "NAAC A+",
    website: "https://www.nitrkl.ac.in",
    overview:
      "NIT Rourkela is one of the top NITs with excellent infrastructure, research output, and strong placement records across branches.",
    courses: [
      { name: "Computer Science & Engineering", degree: "B.Tech", duration: "4 years", feesPerYear: 162000, seats: 130 },
      { name: "Electronics & Communication", degree: "B.Tech", duration: "4 years", feesPerYear: 162000, seats: 110 },
    ],
    placement: { year: 2025, avgPackage: 14.0, highestPackage: 50, placementRate: 90.0, topRecruiters: ["Microsoft", "Amazon", "Qualcomm", "Samsung"] },
    reviews: [{ authorName: "Sourav M.", rating: 4.5, title: "Top-tier NIT", content: "Beautiful campus with placements rivaling older IITs for CS." }],
  },
  {
    slug: "upes-dehradun",
    name: "University of Petroleum and Energy Studies",
    city: "Dehradun",
    state: "Uttarakhand",
    type: "Private University",
    feesPerYear: 380000,
    rating: 4.2,
    established: 2003,
    accreditation: "NAAC A",
    website: "https://www.upes.ac.in",
    overview:
      "UPES Dehradun is a specialized private university known for energy, aerospace, and computer science with industry-aligned curricula.",
    courses: [
      { name: "Computer Science & Engineering", degree: "B.Tech", duration: "4 years", feesPerYear: 380000, seats: 300 },
      { name: "Aerospace Engineering", degree: "B.Tech", duration: "4 years", feesPerYear: 380000, seats: 60 },
    ],
    placement: { year: 2025, avgPackage: 8.5, highestPackage: 40, placementRate: 85.0, topRecruiters: ["Schlumberger", "Halliburton", "Amazon", "Deloitte"] },
    reviews: [{ authorName: "Nitin U.", rating: 4.1, title: "Industry-focused", content: "Niche programs with good corporate tie-ups despite high fees." }],
  },
  {
    slug: "graphic-era-dehradun",
    name: "Graphic Era Deemed to be University",
    city: "Dehradun",
    state: "Uttarakhand",
    type: "Private University",
    feesPerYear: 195000,
    rating: 4.18,
    established: 1997,
    accreditation: "NAAC A+",
    website: "https://www.geu.ac.in",
    overview:
      "Graphic Era University in Dehradun offers engineering and management programs with growing placements in North India hill-state market.",
    courses: [
      { name: "Computer Science & Engineering", degree: "B.Tech", duration: "4 years", feesPerYear: 195000, seats: 360 },
      { name: "Data Science", degree: "B.Tech", duration: "4 years", feesPerYear: 195000, seats: 120 },
    ],
    placement: { year: 2025, avgPackage: 6.0, highestPackage: 28, placementRate: 78.0, topRecruiters: ["TCS", "Wipro", "HCL", "Startups"] },
    reviews: [{ authorName: "Kiran D.", rating: 4.0, title: "Dehradun option", content: "Pleasant campus climate with decent IT placements." }],
  },
  {
    slug: "shiv-nadar-university",
    name: "Shiv Nadar University",
    city: "Greater Noida",
    state: "Uttar Pradesh",
    type: "Private University",
    feesPerYear: 420000,
    rating: 4.48,
    established: 2011,
    accreditation: "NAAC A",
    website: "https://snu.edu.in",
    overview:
      "Shiv Nadar University is a research-driven private university in NCR with interdisciplinary engineering and generous scholarship programs.",
    courses: [
      { name: "Computer Science & Engineering", degree: "B.Tech", duration: "4 years", feesPerYear: 420000, seats: 120 },
      { name: "Electronics & Communication", degree: "B.Tech", duration: "4 years", feesPerYear: 420000, seats: 60 },
    ],
    placement: { year: 2025, avgPackage: 12.0, highestPackage: 55, placementRate: 90.0, topRecruiters: ["Google", "Microsoft", "Samsung", "Research Labs"] },
    reviews: [{ authorName: "Ishita N.", rating: 4.5, title: "Research culture", content: "Small cohorts with excellent faculty-student interaction." }],
  },
];
